sudo: required
dist: trusty
language: node_js
node_js:
- node

before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb

notification:
  email: false
  slack:
    secure: HPhmg3bPQe8beOxiublpPBcyjrAWl5z3ws2/JjPAHNmSRrpSx7tZDjU+Bsa65Gc5wtW3qgajt52oW/s24vIA1qZoHu9hB3gNm8uwOuIVzmHFsf8NCo9XyOGsWvc7hqj3ItPqk/24A0v9PfzqQsDkVBb3rQCYAfjY06Ww3BxQszX/fV/sp9UTJ655lYcwUdrXUmjuaYB+mz6z08EaWWH//tXT5q6oQ53/hTmkIEup04Bt+sZrfREpswBGhqtR2f6iEz8Dzzv72ntUttd6v6kA3A6usnKDyh8YcRwC7jHohaoNyMJaz5nFNiEsAdQmbp5K/BplohMAa33uRJ1nKGj5uTXZJz6lF3+VkfcGFcZ9FYkXl4i6mcs5u0p0j3D4S6fq+S7Y8aSY8ZD//JqDIqFcHvdRxG2m8PqBoBrT4IthPxNdjC+TRYg1ieUZsy99QRWQ5PvlOMmpk2bmOGACHTcUhUBmFUKsf0mx/mFzMlpQYpzcfGWvu9iEPTLERX7cQS67dSOtQixg7AyMAs2yDiJvE4T01oFvculepg9qU8bNRNIzeuQYKfCALNpvRaRZVp7Dv+jbwc16aVS/q31MTrBvjRhxAQAHxIn1gYkinPp5hGU/xNraPV2GZ9AqiJF65hardET7kyy90ufpO/JEjS7bKhSdvrZ7WyZo2H/BOLbMSlw=
